### ISSUE TITLE
OMG's interfaces

### ISSUE THREAD

**Issue by DaveJarvis** [ros2-java/ros2_java#170]
The [OMG DDS specification for Java](https://www.omg.org/spec/DDS-Java) defines a number of classes and interfaces. By developing DDS applications using the OMG's classes and interfaces, developers can replace a specific implementation without a significant amount of rework --- ideally, changing a single line of code. This is similar to how the JDBC API works: developers can swap database drivers by changing a single `Class.forName` call, allowing the plethora of JDBC API calls to remain unchanged. This would make swapping RTI's DDS for ROS2 a snap.

A number of classes in ROS2 mirror class and interface names from the OMG DDS specification. For example, the [Publisher](https://github.com/ros2-java/ros2_java/blob/master/rcljava/src/main/java/org/ros2/rcljava/publisher/Publisher.java) could implement the OMG [Publisher](http://download.ist.adlinktech.com/docs/Vortex/apis/ospl/java5/html/a02274.html) interface, possibly throwing `UnsupportedOperation` exceptions for unimplemented functionality.

This would bring ROS2 a step closer to OMG compliance (with respect to DCPS).

Thoughts?

**Comment by esteve** [comment]
ROS2 is agnostic when it comes to its transport, it just so happens that DDS implementations are the default now (ADLINK's Cyclone, RTI's ConnextDDS, etc.), but one can use other transports that are not DDS at all (e.g. https://github.com/continental/rmw_ecal). ROS2 already has a mechanism akin to JDBC to pick a transport implementation at runtime, and therefore ros2-java as well (https://index.ros.org/doc/ros2/Tutorials/Working-with-multiple-RMW-implementations/)

Compliance with DCPS has never been in the ROS2 roadmap, precisely because ROS2 aims to allow users to use whatever transport is better suited for their use cases.

The ros2-java API is modeled after rclcpp, the C++ client library for ROS2.
