### ISSUE TITLE
How to custom msg

### ISSUE THREAD

**Issue by huyubao** [ros2-java/ros2_java#190]
I want to define my own msg and put it in the example_interfaces directory, but I didn’t compile and change the directory

**Comment by jacobperron** [comment]
I recommend reading this tutorial: https://docs.ros.org/en/galactic/Tutorials/Custom-ROS2-Interfaces.html

To get Java support for your messages, add your package to the same workspace as ros2-java and then you should be able to include your message definitions in your ROS 2 Java code.

I'm going to close this ticket since it's a question and not bug or feature request. If you have further questions I encourage you to ask at [ROS Answers](https://answers.ros.org/questions/).
